import Head from "next/head";
import Layout from "@/components/layout/layout";
import Hero from "@/components/hero";
import Review from "@/components/reviews";
import Form from "@/components/new_contact";
import Process from "@/components/process";
import Steps from "@/components/steps";
import MyCarousel from "@/components/carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>2GoCabinets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BuchFavicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        {/* <Hero /> */}
        <section id="home">
        <MyCarousel />
        </section>
        <section id="service">
        <Process />
        </section>
        <Steps />
        <Review />
        <section id="contact">
          <Form />
        </section>
      </Layout>
    </div>
  );
}
