import Head from "next/head";
import Layout from "@/components/layout/layout";
import Link from "next/link";
import Form from "@/components/new_contact";
import MyCarousel from "@/components/carousel";
import Cabinet from "@/public/Renovation/UMR_3671.jpg";
import Image from "next/image";

import CabSelector from "@/components/cabselctor";
import Card from "@/components/cards";
import ReviewCard from "@/components/reviewbox";
import Slider from "@/components/Slider";
import Modal from "@/components/modal";
import Process from "@/components/procces";

import styles from "@/styles/Cards.module.css";

import Arrow from "@/public/assets/arrow.svg";
import Google from "@/public/assets/google.svg";
import Yelp from "@/public/assets/yelp.svg";
import ArrowDown from "@/public/assets/arrowdown.svg";
import Done from "@/public/assets/done.svg";
import Sign from "@/public/assets/Sign.svg";

import Kitchen1 from "@/public/cards/Slider/Feher_Kitchen.jpg";
import Kitchen2 from "@/public/cards/Slider/Keire_Bathroom.jpg";
import Kitchen3 from "@/public/cards/Slider/mod6_carousel_2.jpg";
import Kitchen4 from "@/public/cards/Slider/Riggen_Bathroom.jpg";
import Dan from "@/public/cards/contractors/thumbnail-avatar-dan.jpg";
import Woman from "@/public/cards/contractors/contractor-match-recommended.jpg";
import Constructor from "@/public/cards/contractors/contractor-thumbnail-dan.jpg";
import Bathroom from "@/public/cards/main/Bathroom.jpg";
import Review1 from "@/public/reviews/home-review-melanie.webp";
import Review2 from "@/public/reviews/home-review-tina.webp";
import { useState } from "react";

const images = [Kitchen1, Kitchen2, Kitchen3, Kitchen4];

const state = ["Columbus", "Grove City", "Hilliard", "Plain City"];

const descriptions = [
  "“When we were getting the kitchen done, I built a really good relationship with the contractors. It was wonderful! They were so lovely, and I felt like I could trust them.”",
  "“For young homeowners who have no idea what theyre doing, the support, the technology and the options were fantastic to have.”",
  "“It was nice to have the vetting process from 2Go to find a contractor thats the right fit. The contractor was really great.”",
  "“Our entire experience with 2Go was such a breeze. The portal for project planning was so easy to use and let me reference anything I needed to know about my project.”",
];

export default function Home() {
  const [isModalOpen, setModalOpen] = useState(false);

  const cards = [
    {
      title: "Pick From Our Wide Selection",
      description: "",
      image: "/process/Cabinets.png",
    },
    {
      title: "Design Your Dream Kitchen",
      description: "",
      image: "/process/Kitchen.png",
    },
    {
      title: "Finish With Your Installation",
      description: "",
      image: "/process/Man.png",
    },
  ];

  const openModal = () => {
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
  };

  return (
    <div className="bg-how">
      <Head>
        <title>2GoCabinets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, iniwtial-scale=1" />
        <link rel="icon" href="/BuchFavicon.ico" />
      </Head>
      <Layout>
        <section id="home">
          <MyCarousel />
        </section>

        <section className="px-9">
          <div className="flex flex-col items-center md:items-start md:flex-row justify-between flex-grow pb-10 pt-16">
            <h4 className="text-4xl text-center md:text-left">
              50+ Kitchens Renovated with our 2Go System <br />
              <p className="text-xl">See what customers have to say!</p>
            </h4>
            <div className="flex items-center gap-2 justify-center md:justify-start">
              <a href="" className="underline text-color5">
                Explore Project Gallery
              </a>
              <button className="rounded-full border-color5 border w-8 h-8 flex items-center justify-center">
                <Image src={Arrow} alt={""} />
              </button>
            </div>
          </div>

          <div className="pb-10">
            <Slider
              images={images}
              state={state}
              descriptions={descriptions}
              showLink={true}
            />
          </div>
        </section>

        <section className="flex flex-col items-center justify-center md:grid md:grid-cols-2 gap-4 px-9">
          <div className="col-span-2 flex flex-col justify-between items-center w-full md:flex-row">
            <h2 className="text-2xl text-center md:text-4xl">
              Trusted by homeowners of Central Ohio
            </h2>
            <div className="flex items-center gap-2">
              <a href="" className="underline text-color5">
                Read Homeowner Reviews
              </a>
              <button className="rounded-full border-color5 border w-8 h-8 flex items-center justify-center">
                <Image src={Arrow} alt="" />
              </button>
            </div>
          </div>

          <div className="flex justify-center gap-4 w-full md:justify-start">
            <div className="flex flex-col gap-1 items-center">
              <Image className="w-16 h-5" src={Google} alt="" />
              <p className="text-xs text-modaltext">4.6 STARS (90)</p>
            </div>
            <div className="flex flex-col gap-1 items-center">
              <Image className="w-14 h-5" src={Yelp} alt="" />
              <p className="text-xs text-modaltext">4.7 STARS (120)</p>
            </div>
          </div>
        </section>

        <section className="px-9 pt-10">
          <div className="flex justify-between">
            <ReviewCard
              imageSrc={Review2}
              name="Tina L."
              stars={5}
              description="“Everything was seamless when I worked with Block. I was actually kind of shocked! I really appreciated being able to save time and not make multiple trips to the hardware store.”"
            />
            <ReviewCard
              imageSrc={Review2}
              name="John D."
              stars={5}
              description="“Compared to what we’ve done before, the build was so much more seamless and communicative. Our contractor was amazing to work with, was extremely responsive and thoughtful throughout the whole process.”"
            />
            <ReviewCard
              imageSrc={Review1}
              name="Anna S."
              stars={5}
              description="“The quality of the work is so incredible, the look is so incredible. I love it. I’m a first time homeowner and renovator, so a big part of the allure of 2Go was having someone experienced help me.”"
            />
          </div>
        </section>

        <section className="pb-10">
          <Process />
        </section>

        <section className="p-10 px-9 ">
          <div>
            <div style={{ paddingBottom: `${Math.max(cards.length, 1)}em` }}>
              {cards.map((card, index) => (
                <div
                  key={index}
                  className={`${styles.card} grid grid-cols-1 md:grid-cols-2 items-center justify-items-center gap-8 px-9 border-t-[1px] border-sembro py-16`}
                  style={{ transform: `translateY(${index}em)` }}
                >
                  <div className="flex flex-col gap-7 items-start">
                    <div className="flex flex-col sm:flex sm:flex-row gap-7 items-center">
                      <div className="bg-color4 w-16 h-16 rounded-full text-center flex items-center justify-center">
                        <h4 className="text-center text-3xl font-light text-white ">
                          {index + 1}
                        </h4>
                      </div>
                      <p className="text-center sm:text-3xl">{card.title}</p>
                    </div>
                  </div>

                  <div>
                    <img
                      className="rounded"
                      alt={card.title}
                      src={card.image}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className=" py-10">
          <CabSelector />
        </section>

        {/* <section className="px-9 py-12">
          <div className="flex flex-col justify-center h-full">
            <div className="flex justify-between flex-grow py-10">
              <h4 className="text-4xl">
                Renovate confidently with seasoned experts and digital tools
              </h4>
              <div className="flex items-center gap-2">
                <Link className="underline text-color5" href={"/How-it-works"}>
                   Learn How It Works
                </Link>
                <button className="rounded-full border-color5 border w-8 h-8 flex items-center justify-center">
                  <Image src={Arrow} alt={""} />
                </button>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-lightgray rounded-md pt-6 overflow-hidden">
                <h5 className="text-2xl pl-6 pb-4">
                  Personalized Match with a Vetted Contractor
                </h5>
                <div className="flex flex-col gap-6 items-center">
                  <div className="text-center py-1 px-2 text-color5 border border-color5 rounded-md max-w-xs">
                    <p className="text-sm">RECOMMENDED FOR YOU</p>
                  </div>
                  <div className="flex justify-center h-[260px] items-center gap-10 overflow-hidden">
                    <Image
                      className="rounded-2xl opacity-40"
                      src={Woman}
                      alt={""}
                      width={152}
                      height={228}
                    />
                    <Image
                      className="rounded-2xl opacity-40 self-end"
                      src={Woman}
                      alt={""}
                      width={152}
                      height={228}
                    />
                    <Image
                      className="rounded-2xl border border-color5"
                      src={Woman}
                      alt={""}
                      width={152}
                      height={228}
                    />
                    <Image
                      className="rounded-2xl opacity-40 self-end"
                      src={Woman}
                      alt={""}
                      width={152}
                      height={228}
                    />
                    <Image
                      className="rounded-2xl opacity-40"
                      src={Woman}
                      alt={""}
                      width={152}
                      height={228}
                    />
                  </div>
                </div>
              </div>

              <div className="bg-lightgray h-[457px] rounded-md p-6">
                <h5 className="text-2xl">
                  Guidance on Fair Pricing through Industry-Leading Data
                </h5>
                <div className="flex justify-center items-center py-6">
                  <div className="bg-white w-[412px] h-[328px] rounded-2xl pt-4 px-10 pb-10">
                    <p className="pb-10 text-center">Your Quote</p>
                    <div className="flex pb-2 items-center gap-4">
                      <Image
                        className="text-color5 stroke-current w-3 h-3 transform rotate-90"
                        src={ArrowDown}
                        alt={""}
                      />
                      <p>Plumbing</p>
                      <div className="border-b border-dotted grow-2 mt-[10px]"></div>
                      <p>$5,000</p>
                    </div>
                    <div className="flex flex-col ml-8 mb-4 py-2 px-4 bg-how rounded-lg">
                      <div className="flex pb-2 gap-2">
                        <p>Labor</p>
                        <div className="border-b border-dotted grow-2"></div>
                        <p>$2,500</p>
                      </div>
                      <div className="flex gap-2">
                        <p>Materials</p>
                        <div className="border-b border-dotted grow-2"></div>
                        <p>$2,500</p>
                      </div>
                    </div>
                    <div className="flex pb-2 items-center gap-2">
                      <Image className="w-3 h-3" src={ArrowDown} alt={""} />
                      <p>Electrical</p>
                      <div className="border-b border-dotted grow-2 mt-[10px]"></div>
                      <p>$4,000</p>
                    </div>
                    <div className="flex pb-2 items-center gap-2">
                      <Image className="w-3 h-3" src={ArrowDown} alt={""} />
                      <p>Materials</p>
                      <div className="border-b border-dotted grow-2 mt-[10px]"></div>
                      <p>$8,000</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <Image className="w-3 h-3" src={ArrowDown} alt={""} />
                      <p>Labor</p>
                      <div className="border-b border-dotted grow-2 mt-[10px]"></div>
                      <p>$12,000</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="bg-lightgray h-[357px] rounded-md p-6">
                <h5 className="text-2xl">
                  Dashboard to Manage Your Renovation
                </h5>
                <div className="flex justify-center items-center py-6">
                  <div className="bg-white shadow-md border-4 border-grayborder w-[377px] h-[228px] py-3.5 px-5 rounded-2xl">
                    <div className="flex items-center justify-between pt-2 pb-5 border-b border-graydot">
                      <p className="font-semibold">
                        Your project is
                        <span className="text-color5">on track</span>
                      </p>
                      <div className="w-16 h-3 rounded-lg bg-grayborder"></div>
                    </div>
                    <div className="flex">
                      <div className="pt-6 px-5 border-r border-graydot flex flex-col gap-6">
                        <div className="flex flex-col gap-2">
                          <div className="h-2 w-16 bg-graydot rounded-xl"></div>
                          <div className="h-12 w-52 bg-graydot rounded-xl"></div>
                        </div>
                      </div>

                      <div className="py-5 px-4 flex flex-col gap-6">
                        {Array.from({ length: 4 }, (_, i) => (
                          <div key={i} className="flex gap-2">
                            <div className="h-2 w-2 rounded-full bg-graydot"></div>
                            <div className="h-2 w-12 bg-graydot rounded-lg"></div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-lightgray h-[357px] rounded-md p-6">
                <h5 className="text-2xl">Secure, Milestone-Based Payments</h5>
                <div className="flex justify-center items-center py-6">
                  <div className="bg-white w-[353px] h-[180px] py-3.5 px-5 rounded-2xl">
                    <div className="flex justify-between">
                      <div>
                        <p className="text-modaltext text-xs">Invoice #5</p>
                        <p>Tile Installation</p>
                      </div>
                      <div>
                        <div className="flex justify-between border-b">
                          <p className="mr-2 text-xs">Materials</p>
                          <p className="ml-2 pb-2 text-xs">$4,000.00</p>
                        </div>
                        <div className="flex justify-between pt-3 border-b border-modaltext">
                          <p className="mr-2 text-xs">Labor</p>
                          <p className="ml-2 pb-2 text-xs">$1,000.00</p>
                        </div>
                        <div className="flex justify-between py-3">
                          <p className="mr-2 text-xs font-medium">Total</p>
                          <p className="ml-2 text-xs font-medium">$5,000.00</p>
                        </div>
                        <p className="bg-color5 text-center text-white rounded-lg p-2">
                          Pay Invoice
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="px-9 py-12">
          <div className="flex flex-col">
            <div className="flex items-center justify-between">
              <div className="'flex">
                <p className="rounded p-1 text-color5 inline-block border">
                  Optioanal
                </p>
                <h4 className="text-4xl">
                  Choose the support upgrades you need
                </h4>
              </div>

              <div className="flex items-center gap-2">
                <a href="" className="underline text-color5">
                  Learn More about Premium Services
                </a>
                <button className="rounded-full border-color5 border w-8 h-8 flex items-center justify-center">
                  <Image src={Arrow} alt={""} />
                </button>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 py-10">
            <div className="h-[715px] custom-border rounded-md p-6">
              <h5 className="text-2xl">Partner with a Dedicated Designer</h5>
              <div className="flex justify-center items-center py-6">
                <div className="bg-white shadow-lg w-[562px] h-[496px] flex flex-col gap-4 pt-4 px-10 pb-10 rounded-2xl">
                  <p className="text-center">Your Bathroom</p>
                  <div className="flex justify-center">
                    <Image
                      className="rounded-2xl"
                      src={Bathroom}
                      alt={""}
                      width={482}
                      height={400}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-rows-2 gap-4">
              <div className="custom-border h-[350px] rounded-md p-6">
                <h5 className="text-2xl">Materials Management and Delivery</h5>
                <div className="flex justify-center items-center py-6">
                  <div className="bg-white shadow-lg py-4 px-6 w-[421px] h-[202px] rounded-2xl">
                    <div className="flex flex-col">
                      <div className="flex border-b items-center justify-between">
                        <p className="p-4 border-r">Shipment #1</p>
                        <div className="px-4 justify-center border rounded-full w-[60%]">
                          <p className=" text-center px-4 py-2 font-light">
                            Delivered today
                          </p>
                        </div>
                      </div>
                      <div className="flex border-b items-center justify-between">
                        <p className="p-4 border-r">Shipment #1</p>
                        <div className="justify-center border rounded-full w-[60%]">
                          <p className="text-center px-4 py-2 font-light">
                            On the way
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center justify-between">
                        <p className="p-4 border-r">Shipment #1</p>
                        <div className="px-4 justify-center border rounded-full w-[60%]">
                          <p className="text-center px-4 py-2 font-light">
                            At 2Go’s warehouse
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="custom-border h-[350px] rounded-md p-6">
                <h5 className="text-2xl">Permitting and Approval Support</h5>
                <div className="flex justify-center items-center py-6">
                  <div className="bg-white shadow-lg w-[200px] h-[196px] rounded-2xl p-4 opacity-50">
                    {" "}
                    <div className="flex flex-col gap-12">
                      <div className="flex flex-col gap-4">
                        <p className="text-center">Agreement</p>
                        <div className="flex flex-col gap-2 justify-center">
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[92%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                        </div>
                      </div>

                      <div className="flex justify-center border-b">
                        <svg
                          width="113"
                          height="26"
                          viewBox="0 0 113 26"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M10.153 14.243c2.991-2.466 5.065-5.517 6.139-9.294 0 0 .468-2.119.408-2.859-.07-.75-.33-1.34-.83-1.708-.49-.358-1.11-.429-1.73-.357-.626.072-1.317.295-2.022.604-1.412.619-2.974 1.625-4.342 2.665C6.41 4.333 5.203 5.43 4.51 6.25 2.833 8.235 1.261 11.33.493 14.526c-.765 3.185-.759 6.587.88 9.1.74 1.134 1.723 1.734 2.82 1.929 1.078.19 2.227-.013 3.324-.404 2.189-.781 4.327-2.366 5.597-3.496a86.77 86.77 0 0 1 2.299-1.973 11.68 11.68 0 0 0-.567.804c-.4.625-.75 1.334-.86 2.056a.833.833 0 0 0 .075.534.66.66 0 0 0 .53.336c.166.015.323-.025.446-.066.13-.045.267-.108.404-.182.537-.289 1.258-.828 1.991-1.435a38.463 38.463 0 0 0 1.633-1.44v.002c-.044.152-.102.321-.167.513-.04.118-.084.244-.129.381-.108.333-.222.717-.256 1.06-.03.3-.024.806.398 1.089.204.136.44.171.664.157.222-.014.468-.078.733-.179 1.27-.482 2.463-1.278 3.572-2.126a59.907 59.907 0 0 0 1.62-1.297l.06-.05c.41-.338.81-.665 1.2-.971-.352.691-.915 1.622-1.41 2.44l-.13.216c-.316.523-.6.996-.727 1.263-.03.063-.068.149-.09.233-.007.03-.033.137-.005.264a.516.516 0 0 0 .504.405c.15 0 .26-.068.288-.084l.002-.001a.925.925 0 0 0 .116-.085 2.83 2.83 0 0 0 .21-.201 45.551 45.551 0 0 1 1.972-1.895l.17-.156a58.683 58.683 0 0 0 1.856-1.758c.842-.846 1.456-1.416 1.893-1.772l.096-.077c-.046.136-.102.288-.166.456-.081.213-.175.448-.273.693-.275.69-.585 1.471-.767 2.128-.12.44-.21.904-.155 1.29.03.2.103.425.277.604a.968.968 0 0 0 .662.286c.949.05 1.86-.346 2.704-.886.839-.537 1.677-1.26 2.486-1.96l.024-.02c.83-.718 1.633-1.409 2.432-1.923.038-.025.077-.05.116-.073-.431.382-.89.803-1.323 1.23-.403.396-.789.804-1.109 1.193-.315.383-.588.775-.743 1.14-.144.34-.252.83.071 1.229.296.364.807.454 1.323.448h.045l.043-.01c1.09-.209 1.969-.956 2.653-1.556.36-.316.65-.585.904-.834-.282.8-.272 1.498.058 2.069.42.724 1.25 1.05 2.076 1.177.845.13 1.814.072 2.694-.09.795-.148 1.56-.388 2.126-.684.122.016.238.021.328.025l.054.003c2.199.115 3.82-.676 5.494-1.924.606-.452 1.167-.94 1.707-1.435a54.157 54.157 0 0 1-1.706 2.267l-.006.008a.799.799 0 0 1-.022.023l-.072.074-.006.005c-.055.056-.129.13-.198.208-.07.08-.153.18-.218.293a.826.826 0 0 0-.12.5.518.518 0 0 0 .272.415.512.512 0 0 0 .6-.082.712.712 0 0 0 .107-.126 7.55 7.55 0 0 0 .113-.193l.026-.048.032-.054-.003.003c.292-.356.615-.695.95-1.044 1.298-1.355 2.636-2.7 4.079-3.855-.02.284-.047.565-.076.858-.027.276-.055.563-.078.869-.052.68-.072 1.398.045 2.08.069.4.257.75.619.936.336.173.713.145 1.034.064.64-.161 1.392-.623 2.079-1.119.703-.508 1.4-1.098 1.94-1.575.27-.24.503-.452.678-.612l.061-.056.002-.002a44.327 44.327 0 0 1 .223-.203l.022-.018.006-.006.002-.001a.5.5 0 1 0-.625-.78c-.055.043-.167.146-.302.27l-.064.058c-.174.16-.402.368-.666.601a25.12 25.12 0 0 1-1.862 1.514c-.681.49-1.3.849-1.74.96-.219.055-.31.027-.33.016-.007-.003-.017-.01-.032-.032a.51.51 0 0 1-.06-.183c-.095-.56-.083-1.179-.033-1.837.019-.254.045-.526.072-.802.039-.4.078-.808.098-1.177v-.009c.01-.2.02-.386.015-.526a1.065 1.065 0 0 0-.037-.255.602.602 0 0 0-.277-.36.593.593 0 0 0-.47-.046 1 1 0 0 0-.238.115c-.12.075-.267.191-.426.315-.39.305-.77.623-1.145.95l.09-.145c.054-.088.122-.191.195-.302l.045-.067c.082-.124.177-.27.236-.382.015-.03.033-.066.049-.105a.634.634 0 0 0 .044-.19.518.518 0 0 0-.275-.496c-.205-.107-.395-.038-.429-.025h-.002c-.106.039-.203.11-.263.155a5.124 5.124 0 0 0-.275.23c-.493.434-.97.886-1.44 1.33-.181.173-.362.345-.541.513-.65.609-1.298 1.192-2.002 1.716-1.245.928-2.377 1.53-3.723 1.693.838-.63 1.371-1.214 1.655-1.734.21-.384.308-.78.232-1.148a1.095 1.095 0 0 0-.678-.803c-.63-.255-1.452-.015-2.117.548-.69.584-1.288 1.564-1.541 2.982-.027.15-.033.311.002.467a7.853 7.853 0 0 1-1.416.393c-.806.15-1.657.194-2.36.086-.724-.111-1.173-.363-1.362-.69-.177-.305-.232-.864.302-1.865.459-.862.69-1.211.935-1.551l.152-.21c.221-.3.492-.669.926-1.346 1.582-1.82 4.037-5.746 5.047-7.894.063-.136.111-.244.14-.324a.822.822 0 0 0 .044-.163v-.002a.505.505 0 0 0-.826-.469v.001a.658.658 0 0 0-.068.064 1.23 1.23 0 0 0-.078.093 4.552 4.552 0 0 0-.147.209c-.104.155-.227.349-.331.514l-.05.078c-.084.133-.145.23-.17.266-.697 1.01-1.782 2.801-2.764 4.421a155.702 155.702 0 0 1-1.596 2.6c-.082.086-.318.314-.584.57l-.056.054-.002.002c-.254.245-.523.505-.604.594a103.7 103.7 0 0 0-.644.727c-.7.797-1.114 1.267-2.114 2.145-.696.61-1.37 1.155-2.138 1.318-.314 0-.438-.052-.477-.073 0-.03.01-.095.061-.215.098-.232.3-.535.594-.894.29-.352.65-.733 1.039-1.116.778-.767 1.654-1.524 2.286-2.064l.183-.156c.23-.196.42-.359.541-.467.039-.035.075-.068.105-.098h.001c.02-.02.07-.07.11-.13a.506.506 0 0 0-.331-.78.515.515 0 0 0-.255.02c-.942.023-1.841.428-2.676.965-.867.558-1.721 1.296-2.537 2l-.007.006c-.831.718-1.621 1.4-2.396 1.896-.775.496-1.47.762-2.107.73a.37.37 0 0 1-.007-.034c-.024-.166.013-.46.13-.881.165-.6.442-1.297.71-1.971.104-.259.206-.515.3-.76.16-.422.304-.834.36-1.152.026-.146.05-.353-.01-.545a.657.657 0 0 0-.231-.334.652.652 0 0 0-.402-.128c-.218.002-.425.102-.588.197-.18.105-.388.257-.626.45-.477.39-1.12.989-1.97 1.842a57.974 57.974 0 0 1-1.826 1.73l-.004.003c.399-.683.767-1.353.953-1.82.112-.284.195-.547.199-.764a.677.677 0 0 0-.151-.456.603.603 0 0 0-.512-.206.93.93 0 0 0-.318.09 2.131 2.131 0 0 0-.246.138c-.156.1-.328.229-.493.355-.486.373-.981.78-1.48 1.19l-.064.053c-.524.43-1.053.863-1.593 1.276-1.083.828-2.185 1.554-3.32 1.986-.213.08-.354.11-.44.115h-.009a.92.92 0 0 1 .005-.149c.023-.225.104-.518.212-.848l.11-.328c.073-.213.147-.43.196-.605.076-.268.27-.716.507-1.207.224-.466.472-.94.655-1.277.075-.1.144-.202.193-.298.045-.089.081-.163.101-.21a.614.614 0 0 0 .026-.076.5.5 0 0 0-.919-.385 8.26 8.26 0 0 0-.242.423c-.549.706-2.12 2.238-3.553 3.426-.662.548-1.263.997-1.7 1.253a5.53 5.53 0 0 1 .594-1.187c.364-.57.805-1.108 1.197-1.563 1.048-1.217 2.259-2.287 3.554-3.256.473-.354.817-.625 1.041-.818.11-.094.204-.18.27-.25a.929.929 0 0 0 .11-.139.577.577 0 0 0 .067-.153.513.513 0 0 0-.43-.646.564.564 0 0 0-.182.008.865.865 0 0 0-.168.054c-.086.037-.19.092-.302.156-.228.131-.546.332-.934.593-1.554 1.045-4.35 3.13-7.461 5.897-1.227 1.091-3.253 2.581-5.27 3.3-1.006.36-1.969.512-2.812.362-.822-.146-1.566-.585-2.157-1.49-1.42-2.176-1.485-5.246-.746-8.32C2.2 11.7 3.707 8.75 5.273 6.897 5.9 6.154 7.046 5.105 8.38 4.09c1.335-1.014 2.826-1.97 4.139-2.545.657-.288 1.246-.47 1.734-.526.493-.057.82.02 1.026.17.193.142.373.418.42.983.046.572-.052 1.387-.37 2.504-1.016 3.57-2.97 6.451-5.813 8.796a.5.5 0 0 0 .636.771zm37.654 8.075c.564-.357 1.009-.691 1.351-.995.437-.388.697-.717.838-.974.142-.261.142-.41.13-.465a.092.092 0 0 0-.02-.045.142.142 0 0 0-.055-.035c-.07-.029-.209-.048-.413.006-.199.053-.437.171-.68.378-.45.38-.911 1.057-1.151 2.13z"
                            fill="#000"
                          ></path>
                          <path
                            d="M86.246 3.07c-2.324-.334-4.835.557-7.173 2.081-2.348 1.53-4.582 3.738-6.374 6.148-1.792 2.408-3.165 5.05-3.762 7.46-.594 2.396-.446 4.685.996 6.231.461.494 1.1.76 1.772.892.675.132 1.425.14 2.164.086 1.477-.108 2.997-.476 3.93-.704a.5.5 0 0 0-.238-.971c-.939.23-2.383.576-3.765.678-.691.051-1.344.038-1.897-.07-.556-.11-.969-.308-1.234-.593-1.102-1.181-1.318-3.046-.758-5.308.557-2.247 1.857-4.768 3.594-7.104 1.736-2.334 3.887-4.452 6.118-5.907 2.24-1.46 4.502-2.214 6.484-1.93.563.081.909.261 1.121.472.21.207.334.489.373.864.08.783-.23 1.859-.78 3.047-1.086 2.348-2.941 4.798-3.492 5.503a.5.5 0 0 0 .788.616c.555-.71 2.473-3.239 3.612-5.699.562-1.215.976-2.501.867-3.569-.057-.55-.255-1.067-.664-1.472-.406-.403-.972-.65-1.682-.751z"
                            fill="#000"
                          ></path>
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M100.056 11.98a.854.854 0 0 1 .535.259c.482.482.607 1.167.558 1.855-.049.695-.279 1.478-.61 2.273-.632 1.517-1.678 3.173-2.772 4.512.136.304.352.487.614.592.3.12.68.141 1.082.066.4-.076.786-.243 1.081-.458.301-.22.461-.455.504-.65l.001-.003.002-.01.007-.037.004-.026.016-.084c.015-.084.036-.191.061-.293.021-.09.057-.222.112-.33l.001-.002a.598.598 0 0 1 .258-.265.525.525 0 0 1 .478.002c.846.23 1.688-.032 2.636-.487.239-.115.479-.24.725-.367l.058-.03.001-.001c.224-.117.454-.236.684-.35.498-.244 1.025-.471 1.569-.592.066-.015.159-.034.246-.034h.003a.55.55 0 0 1 .299.083.51.51 0 0 1 .196.633.584.584 0 0 1-.134.19h-.001a.94.94 0 0 1-.087.075 3.38 3.38 0 0 1-.179.122c-.079.052-.17.11-.272.173-.246.155-.553.348-.899.588a9.825 9.825 0 0 0-1.451 1.206c-.448.465-.789.957-.943 1.46-.113.366-.108.635-.051.778a.22.22 0 0 0 .093.117c.043.026.13.06.295.06.213 0 .495-.133.839-.458.332-.315.653-.743.939-1.177.204-.31.378-.603.527-.852l.17-.284c.077-.125.172-.278.261-.372a.661.661 0 0 1 .145-.115.525.525 0 0 1 .473-.025.53.53 0 0 1 .291.342c.02.074.023.141.023.179V22.4c0 .086.021.132.042.163.025.035.073.08.169.127.205.098.53.154.949.163.625.014 1.289-.073 1.792-.139.174-.022.328-.042.455-.055a.5.5 0 0 1 .099.995c-.086.008-.207.024-.352.043-.503.066-1.304.172-2.016.156-.461-.01-.96-.07-1.36-.262a1.411 1.411 0 0 1-.553-.452 1.263 1.263 0 0 1-.225-.74v-.562l-.055.083c-.301.457-.671.96-1.086 1.353-.403.381-.925.732-1.527.732-.302 0-.582-.063-.819-.208a1.22 1.22 0 0 1-.498-.599c-.181-.453-.117-.986.024-1.443.2-.65.599-1.23 1.053-1.725-.758.316-1.589.536-2.469.39l-.006.03-.011.062a5.009 5.009 0 0 1-.025.134c-.115.516-.476.938-.891 1.24-.422.309-.947.532-1.485.633-.535.101-1.118.088-1.638-.12a2.086 2.086 0 0 1-.935-.724c-.421.454-.843.855-1.249 1.173-.552.435-1.15.778-1.706.808a.779.779 0 0 1-.428-.098.79.79 0 0 1-.293-.294c-.118-.203-.15-.442-.16-.637-.018-.403.058-.91.14-1.358.017-.097.035-.19.053-.28l-.03.036a36.2 36.2 0 0 0-.42.526c-.234.296-.483.612-.724.892-.403.47-.86.936-1.364 1.227-.52.301-1.133.435-1.774.15a1.352 1.352 0 0 1-.715-.689c-.133-.3-.14-.626-.087-.93.08-.46.311-.955.612-1.433-.307.305-.615.622-.926.941l-.047.048-.227.234c-.747.766-1.511 1.532-2.27 2.105-.75.568-1.568 1.004-2.421 1.004-.47 0-.902-.136-1.169-.505-.25-.346-.265-.776-.211-1.152.108-.752.556-1.693 1.033-2.56.35-.637.742-1.28 1.078-1.828.129-.212.25-.409.356-.587.085-.141.159-.268.222-.38-1.175-.034-2.379.017-3.601.083l-.747.042c-1.196.068-2.407.137-3.595.137a.5.5 0 0 1 0-1c1.157 0 2.333-.067 3.528-.135h.002l.757-.042c1.449-.08 2.917-.139 4.354-.054a.55.55 0 0 1 .443.266.598.598 0 0 1 .078.364c-.013.142-.07.283-.116.384a9.17 9.17 0 0 1-.467.849 83.56 83.56 0 0 1-.374.615 45.29 45.29 0 0 0-1.042 1.767c-.48.874-.84 1.67-.92 2.222-.04.276.007.388.032.422.008.012.067.092.359.092.52 0 1.12-.274 1.818-.801.69-.522 1.405-1.235 2.157-2.006l.272-.28c.659-.678 1.342-1.38 2.03-1.98.78-.677 1.612-1.263 2.48-1.527.183-.056.476-.122.746-.181.29-.143.603-.255.899-.255.044 0 .114.001.182.014h.002c.019.004.14.026.247.12a.505.505 0 0 1 .058.705c-.072.087-.157.128-.175.137l-.002.001a.759.759 0 0 1-.082.035c-.043.015-.09.03-.134.041-.155.042-.402.096-.643.149l-.01.002c-.854.46-2.068 1.561-2.859 2.658-.406.564-.657 1.068-.722 1.44-.03.179-.012.29.017.355.024.055.073.12.206.18.266.118.536.09.868-.103.35-.203.717-.561 1.106-1.013.234-.273.45-.547.667-.823.151-.192.303-.384.462-.578.356-.434.752-.875 1.165-1.112a.579.579 0 0 1 .268-.077.535.535 0 0 1 .383.142.57.57 0 0 1 .153.24c.02.062.028.12.032.162.014.148-.01.332-.035.484-.029.18-.076.42-.126.668-.036.185-.074.375-.106.551-.083.451-.137.856-.124 1.133l.002.044c.232-.067.558-.242.968-.563.465-.366.978-.873 1.496-1.474-.015-.53.088-1.291.248-2.1.19-.955.473-2.046.798-3.047.323-.992.698-1.929 1.081-2.556.185-.302.41-.597.68-.764a.894.894 0 0 1 .543-.14zm-.44 4.002c-.422 1.013-1.052 2.11-1.759 3.12a26.488 26.488 0 0 1 .846-3.35c.316-.973.663-1.82.984-2.346.113-.186.207-.302.274-.37.143.201.224.516.19.988-.038.544-.225 1.215-.535 1.958z"
                            fill="#000"
                          ></path>
                        </svg>
                      </div>
                    </div>
                  </div>
                  <div className="bg-white shadow-lg w-[200px] h-[196px] rounded-2xl p-4">
                    <div className="flex flex-col gap-12">
                      <div className="flex flex-col gap-4">
                        <p className="text-center">Requirements</p>
                        <div className="flex flex-col gap-2 justify-center">
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[92%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                        </div>
                      </div>

                      <div className="flex justify-center border-b">
                        <svg
                          width="113"
                          height="26"
                          viewBox="0 0 113 26"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M10.153 14.243c2.991-2.466 5.065-5.517 6.139-9.294 0 0 .468-2.119.408-2.859-.07-.75-.33-1.34-.83-1.708-.49-.358-1.11-.429-1.73-.357-.626.072-1.317.295-2.022.604-1.412.619-2.974 1.625-4.342 2.665C6.41 4.333 5.203 5.43 4.51 6.25 2.833 8.235 1.261 11.33.493 14.526c-.765 3.185-.759 6.587.88 9.1.74 1.134 1.723 1.734 2.82 1.929 1.078.19 2.227-.013 3.324-.404 2.189-.781 4.327-2.366 5.597-3.496a86.77 86.77 0 0 1 2.299-1.973 11.68 11.68 0 0 0-.567.804c-.4.625-.75 1.334-.86 2.056a.833.833 0 0 0 .075.534.66.66 0 0 0 .53.336c.166.015.323-.025.446-.066.13-.045.267-.108.404-.182.537-.289 1.258-.828 1.991-1.435a38.463 38.463 0 0 0 1.633-1.44v.002c-.044.152-.102.321-.167.513-.04.118-.084.244-.129.381-.108.333-.222.717-.256 1.06-.03.3-.024.806.398 1.089.204.136.44.171.664.157.222-.014.468-.078.733-.179 1.27-.482 2.463-1.278 3.572-2.126a59.907 59.907 0 0 0 1.62-1.297l.06-.05c.41-.338.81-.665 1.2-.971-.352.691-.915 1.622-1.41 2.44l-.13.216c-.316.523-.6.996-.727 1.263-.03.063-.068.149-.09.233-.007.03-.033.137-.005.264a.516.516 0 0 0 .504.405c.15 0 .26-.068.288-.084l.002-.001a.925.925 0 0 0 .116-.085 2.83 2.83 0 0 0 .21-.201 45.551 45.551 0 0 1 1.972-1.895l.17-.156a58.683 58.683 0 0 0 1.856-1.758c.842-.846 1.456-1.416 1.893-1.772l.096-.077c-.046.136-.102.288-.166.456-.081.213-.175.448-.273.693-.275.69-.585 1.471-.767 2.128-.12.44-.21.904-.155 1.29.03.2.103.425.277.604a.968.968 0 0 0 .662.286c.949.05 1.86-.346 2.704-.886.839-.537 1.677-1.26 2.486-1.96l.024-.02c.83-.718 1.633-1.409 2.432-1.923.038-.025.077-.05.116-.073-.431.382-.89.803-1.323 1.23-.403.396-.789.804-1.109 1.193-.315.383-.588.775-.743 1.14-.144.34-.252.83.071 1.229.296.364.807.454 1.323.448h.045l.043-.01c1.09-.209 1.969-.956 2.653-1.556.36-.316.65-.585.904-.834-.282.8-.272 1.498.058 2.069.42.724 1.25 1.05 2.076 1.177.845.13 1.814.072 2.694-.09.795-.148 1.56-.388 2.126-.684.122.016.238.021.328.025l.054.003c2.199.115 3.82-.676 5.494-1.924.606-.452 1.167-.94 1.707-1.435a54.157 54.157 0 0 1-1.706 2.267l-.006.008a.799.799 0 0 1-.022.023l-.072.074-.006.005c-.055.056-.129.13-.198.208-.07.08-.153.18-.218.293a.826.826 0 0 0-.12.5.518.518 0 0 0 .272.415.512.512 0 0 0 .6-.082.712.712 0 0 0 .107-.126 7.55 7.55 0 0 0 .113-.193l.026-.048.032-.054-.003.003c.292-.356.615-.695.95-1.044 1.298-1.355 2.636-2.7 4.079-3.855-.02.284-.047.565-.076.858-.027.276-.055.563-.078.869-.052.68-.072 1.398.045 2.08.069.4.257.75.619.936.336.173.713.145 1.034.064.64-.161 1.392-.623 2.079-1.119.703-.508 1.4-1.098 1.94-1.575.27-.24.503-.452.678-.612l.061-.056.002-.002a44.327 44.327 0 0 1 .223-.203l.022-.018.006-.006.002-.001a.5.5 0 1 0-.625-.78c-.055.043-.167.146-.302.27l-.064.058c-.174.16-.402.368-.666.601a25.12 25.12 0 0 1-1.862 1.514c-.681.49-1.3.849-1.74.96-.219.055-.31.027-.33.016-.007-.003-.017-.01-.032-.032a.51.51 0 0 1-.06-.183c-.095-.56-.083-1.179-.033-1.837.019-.254.045-.526.072-.802.039-.4.078-.808.098-1.177v-.009c.01-.2.02-.386.015-.526a1.065 1.065 0 0 0-.037-.255.602.602 0 0 0-.277-.36.593.593 0 0 0-.47-.046 1 1 0 0 0-.238.115c-.12.075-.267.191-.426.315-.39.305-.77.623-1.145.95l.09-.145c.054-.088.122-.191.195-.302l.045-.067c.082-.124.177-.27.236-.382.015-.03.033-.066.049-.105a.634.634 0 0 0 .044-.19.518.518 0 0 0-.275-.496c-.205-.107-.395-.038-.429-.025h-.002c-.106.039-.203.11-.263.155a5.124 5.124 0 0 0-.275.23c-.493.434-.97.886-1.44 1.33-.181.173-.362.345-.541.513-.65.609-1.298 1.192-2.002 1.716-1.245.928-2.377 1.53-3.723 1.693.838-.63 1.371-1.214 1.655-1.734.21-.384.308-.78.232-1.148a1.095 1.095 0 0 0-.678-.803c-.63-.255-1.452-.015-2.117.548-.69.584-1.288 1.564-1.541 2.982-.027.15-.033.311.002.467a7.853 7.853 0 0 1-1.416.393c-.806.15-1.657.194-2.36.086-.724-.111-1.173-.363-1.362-.69-.177-.305-.232-.864.302-1.865.459-.862.69-1.211.935-1.551l.152-.21c.221-.3.492-.669.926-1.346 1.582-1.82 4.037-5.746 5.047-7.894.063-.136.111-.244.14-.324a.822.822 0 0 0 .044-.163v-.002a.505.505 0 0 0-.826-.469v.001a.658.658 0 0 0-.068.064 1.23 1.23 0 0 0-.078.093 4.552 4.552 0 0 0-.147.209c-.104.155-.227.349-.331.514l-.05.078c-.084.133-.145.23-.17.266-.697 1.01-1.782 2.801-2.764 4.421a155.702 155.702 0 0 1-1.596 2.6c-.082.086-.318.314-.584.57l-.056.054-.002.002c-.254.245-.523.505-.604.594a103.7 103.7 0 0 0-.644.727c-.7.797-1.114 1.267-2.114 2.145-.696.61-1.37 1.155-2.138 1.318-.314 0-.438-.052-.477-.073 0-.03.01-.095.061-.215.098-.232.3-.535.594-.894.29-.352.65-.733 1.039-1.116.778-.767 1.654-1.524 2.286-2.064l.183-.156c.23-.196.42-.359.541-.467.039-.035.075-.068.105-.098h.001c.02-.02.07-.07.11-.13a.506.506 0 0 0-.331-.78.515.515 0 0 0-.255.02c-.942.023-1.841.428-2.676.965-.867.558-1.721 1.296-2.537 2l-.007.006c-.831.718-1.621 1.4-2.396 1.896-.775.496-1.47.762-2.107.73a.37.37 0 0 1-.007-.034c-.024-.166.013-.46.13-.881.165-.6.442-1.297.71-1.971.104-.259.206-.515.3-.76.16-.422.304-.834.36-1.152.026-.146.05-.353-.01-.545a.657.657 0 0 0-.231-.334.652.652 0 0 0-.402-.128c-.218.002-.425.102-.588.197-.18.105-.388.257-.626.45-.477.39-1.12.989-1.97 1.842a57.974 57.974 0 0 1-1.826 1.73l-.004.003c.399-.683.767-1.353.953-1.82.112-.284.195-.547.199-.764a.677.677 0 0 0-.151-.456.603.603 0 0 0-.512-.206.93.93 0 0 0-.318.09 2.131 2.131 0 0 0-.246.138c-.156.1-.328.229-.493.355-.486.373-.981.78-1.48 1.19l-.064.053c-.524.43-1.053.863-1.593 1.276-1.083.828-2.185 1.554-3.32 1.986-.213.08-.354.11-.44.115h-.009a.92.92 0 0 1 .005-.149c.023-.225.104-.518.212-.848l.11-.328c.073-.213.147-.43.196-.605.076-.268.27-.716.507-1.207.224-.466.472-.94.655-1.277.075-.1.144-.202.193-.298.045-.089.081-.163.101-.21a.614.614 0 0 0 .026-.076.5.5 0 0 0-.919-.385 8.26 8.26 0 0 0-.242.423c-.549.706-2.12 2.238-3.553 3.426-.662.548-1.263.997-1.7 1.253a5.53 5.53 0 0 1 .594-1.187c.364-.57.805-1.108 1.197-1.563 1.048-1.217 2.259-2.287 3.554-3.256.473-.354.817-.625 1.041-.818.11-.094.204-.18.27-.25a.929.929 0 0 0 .11-.139.577.577 0 0 0 .067-.153.513.513 0 0 0-.43-.646.564.564 0 0 0-.182.008.865.865 0 0 0-.168.054c-.086.037-.19.092-.302.156-.228.131-.546.332-.934.593-1.554 1.045-4.35 3.13-7.461 5.897-1.227 1.091-3.253 2.581-5.27 3.3-1.006.36-1.969.512-2.812.362-.822-.146-1.566-.585-2.157-1.49-1.42-2.176-1.485-5.246-.746-8.32C2.2 11.7 3.707 8.75 5.273 6.897 5.9 6.154 7.046 5.105 8.38 4.09c1.335-1.014 2.826-1.97 4.139-2.545.657-.288 1.246-.47 1.734-.526.493-.057.82.02 1.026.17.193.142.373.418.42.983.046.572-.052 1.387-.37 2.504-1.016 3.57-2.97 6.451-5.813 8.796a.5.5 0 0 0 .636.771zm37.654 8.075c.564-.357 1.009-.691 1.351-.995.437-.388.697-.717.838-.974.142-.261.142-.41.13-.465a.092.092 0 0 0-.02-.045.142.142 0 0 0-.055-.035c-.07-.029-.209-.048-.413.006-.199.053-.437.171-.68.378-.45.38-.911 1.057-1.151 2.13z"
                            fill="#000"
                          ></path>
                          <path
                            d="M86.246 3.07c-2.324-.334-4.835.557-7.173 2.081-2.348 1.53-4.582 3.738-6.374 6.148-1.792 2.408-3.165 5.05-3.762 7.46-.594 2.396-.446 4.685.996 6.231.461.494 1.1.76 1.772.892.675.132 1.425.14 2.164.086 1.477-.108 2.997-.476 3.93-.704a.5.5 0 0 0-.238-.971c-.939.23-2.383.576-3.765.678-.691.051-1.344.038-1.897-.07-.556-.11-.969-.308-1.234-.593-1.102-1.181-1.318-3.046-.758-5.308.557-2.247 1.857-4.768 3.594-7.104 1.736-2.334 3.887-4.452 6.118-5.907 2.24-1.46 4.502-2.214 6.484-1.93.563.081.909.261 1.121.472.21.207.334.489.373.864.08.783-.23 1.859-.78 3.047-1.086 2.348-2.941 4.798-3.492 5.503a.5.5 0 0 0 .788.616c.555-.71 2.473-3.239 3.612-5.699.562-1.215.976-2.501.867-3.569-.057-.55-.255-1.067-.664-1.472-.406-.403-.972-.65-1.682-.751z"
                            fill="#000"
                          ></path>
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M100.056 11.98a.854.854 0 0 1 .535.259c.482.482.607 1.167.558 1.855-.049.695-.279 1.478-.61 2.273-.632 1.517-1.678 3.173-2.772 4.512.136.304.352.487.614.592.3.12.68.141 1.082.066.4-.076.786-.243 1.081-.458.301-.22.461-.455.504-.65l.001-.003.002-.01.007-.037.004-.026.016-.084c.015-.084.036-.191.061-.293.021-.09.057-.222.112-.33l.001-.002a.598.598 0 0 1 .258-.265.525.525 0 0 1 .478.002c.846.23 1.688-.032 2.636-.487.239-.115.479-.24.725-.367l.058-.03.001-.001c.224-.117.454-.236.684-.35.498-.244 1.025-.471 1.569-.592.066-.015.159-.034.246-.034h.003a.55.55 0 0 1 .299.083.51.51 0 0 1 .196.633.584.584 0 0 1-.134.19h-.001a.94.94 0 0 1-.087.075 3.38 3.38 0 0 1-.179.122c-.079.052-.17.11-.272.173-.246.155-.553.348-.899.588a9.825 9.825 0 0 0-1.451 1.206c-.448.465-.789.957-.943 1.46-.113.366-.108.635-.051.778a.22.22 0 0 0 .093.117c.043.026.13.06.295.06.213 0 .495-.133.839-.458.332-.315.653-.743.939-1.177.204-.31.378-.603.527-.852l.17-.284c.077-.125.172-.278.261-.372a.661.661 0 0 1 .145-.115.525.525 0 0 1 .473-.025.53.53 0 0 1 .291.342c.02.074.023.141.023.179V22.4c0 .086.021.132.042.163.025.035.073.08.169.127.205.098.53.154.949.163.625.014 1.289-.073 1.792-.139.174-.022.328-.042.455-.055a.5.5 0 0 1 .099.995c-.086.008-.207.024-.352.043-.503.066-1.304.172-2.016.156-.461-.01-.96-.07-1.36-.262a1.411 1.411 0 0 1-.553-.452 1.263 1.263 0 0 1-.225-.74v-.562l-.055.083c-.301.457-.671.96-1.086 1.353-.403.381-.925.732-1.527.732-.302 0-.582-.063-.819-.208a1.22 1.22 0 0 1-.498-.599c-.181-.453-.117-.986.024-1.443.2-.65.599-1.23 1.053-1.725-.758.316-1.589.536-2.469.39l-.006.03-.011.062a5.009 5.009 0 0 1-.025.134c-.115.516-.476.938-.891 1.24-.422.309-.947.532-1.485.633-.535.101-1.118.088-1.638-.12a2.086 2.086 0 0 1-.935-.724c-.421.454-.843.855-1.249 1.173-.552.435-1.15.778-1.706.808a.779.779 0 0 1-.428-.098.79.79 0 0 1-.293-.294c-.118-.203-.15-.442-.16-.637-.018-.403.058-.91.14-1.358.017-.097.035-.19.053-.28l-.03.036a36.2 36.2 0 0 0-.42.526c-.234.296-.483.612-.724.892-.403.47-.86.936-1.364 1.227-.52.301-1.133.435-1.774.15a1.352 1.352 0 0 1-.715-.689c-.133-.3-.14-.626-.087-.93.08-.46.311-.955.612-1.433-.307.305-.615.622-.926.941l-.047.048-.227.234c-.747.766-1.511 1.532-2.27 2.105-.75.568-1.568 1.004-2.421 1.004-.47 0-.902-.136-1.169-.505-.25-.346-.265-.776-.211-1.152.108-.752.556-1.693 1.033-2.56.35-.637.742-1.28 1.078-1.828.129-.212.25-.409.356-.587.085-.141.159-.268.222-.38-1.175-.034-2.379.017-3.601.083l-.747.042c-1.196.068-2.407.137-3.595.137a.5.5 0 0 1 0-1c1.157 0 2.333-.067 3.528-.135h.002l.757-.042c1.449-.08 2.917-.139 4.354-.054a.55.55 0 0 1 .443.266.598.598 0 0 1 .078.364c-.013.142-.07.283-.116.384a9.17 9.17 0 0 1-.467.849 83.56 83.56 0 0 1-.374.615 45.29 45.29 0 0 0-1.042 1.767c-.48.874-.84 1.67-.92 2.222-.04.276.007.388.032.422.008.012.067.092.359.092.52 0 1.12-.274 1.818-.801.69-.522 1.405-1.235 2.157-2.006l.272-.28c.659-.678 1.342-1.38 2.03-1.98.78-.677 1.612-1.263 2.48-1.527.183-.056.476-.122.746-.181.29-.143.603-.255.899-.255.044 0 .114.001.182.014h.002c.019.004.14.026.247.12a.505.505 0 0 1 .058.705c-.072.087-.157.128-.175.137l-.002.001a.759.759 0 0 1-.082.035c-.043.015-.09.03-.134.041-.155.042-.402.096-.643.149l-.01.002c-.854.46-2.068 1.561-2.859 2.658-.406.564-.657 1.068-.722 1.44-.03.179-.012.29.017.355.024.055.073.12.206.18.266.118.536.09.868-.103.35-.203.717-.561 1.106-1.013.234-.273.45-.547.667-.823.151-.192.303-.384.462-.578.356-.434.752-.875 1.165-1.112a.579.579 0 0 1 .268-.077.535.535 0 0 1 .383.142.57.57 0 0 1 .153.24c.02.062.028.12.032.162.014.148-.01.332-.035.484-.029.18-.076.42-.126.668-.036.185-.074.375-.106.551-.083.451-.137.856-.124 1.133l.002.044c.232-.067.558-.242.968-.563.465-.366.978-.873 1.496-1.474-.015-.53.088-1.291.248-2.1.19-.955.473-2.046.798-3.047.323-.992.698-1.929 1.081-2.556.185-.302.41-.597.68-.764a.894.894 0 0 1 .543-.14zm-.44 4.002c-.422 1.013-1.052 2.11-1.759 3.12a26.488 26.488 0 0 1 .846-3.35c.316-.973.663-1.82.984-2.346.113-.186.207-.302.274-.37.143.201.224.516.19.988-.038.544-.225 1.215-.535 1.958z"
                            fill="#000"
                          ></path>
                        </svg>
                      </div>
                    </div>
                  </div>
                  <div className="bg-white shadow-lg w-[200px] h-[196px] rounded-2xl p-4 opacity-50">
                    {" "}
                    <div className="flex flex-col gap-12">
                      <div className="flex flex-col gap-4">
                        <p className="text-center">Guidelines</p>
                        <div className="flex flex-col gap-2 justify-center">
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[92%] bg-lines"></div>
                          <div className="h-[2px] w-[71%] bg-lines"></div>
                          <div className="h-[2px] w-[58%] bg-lines"></div>
                        </div>
                      </div>

                      <div className="flex justify-center border-b">
                        <svg
                          width="113"
                          height="26"
                          viewBox="0 0 113 26"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M10.153 14.243c2.991-2.466 5.065-5.517 6.139-9.294 0 0 .468-2.119.408-2.859-.07-.75-.33-1.34-.83-1.708-.49-.358-1.11-.429-1.73-.357-.626.072-1.317.295-2.022.604-1.412.619-2.974 1.625-4.342 2.665C6.41 4.333 5.203 5.43 4.51 6.25 2.833 8.235 1.261 11.33.493 14.526c-.765 3.185-.759 6.587.88 9.1.74 1.134 1.723 1.734 2.82 1.929 1.078.19 2.227-.013 3.324-.404 2.189-.781 4.327-2.366 5.597-3.496a86.77 86.77 0 0 1 2.299-1.973 11.68 11.68 0 0 0-.567.804c-.4.625-.75 1.334-.86 2.056a.833.833 0 0 0 .075.534.66.66 0 0 0 .53.336c.166.015.323-.025.446-.066.13-.045.267-.108.404-.182.537-.289 1.258-.828 1.991-1.435a38.463 38.463 0 0 0 1.633-1.44v.002c-.044.152-.102.321-.167.513-.04.118-.084.244-.129.381-.108.333-.222.717-.256 1.06-.03.3-.024.806.398 1.089.204.136.44.171.664.157.222-.014.468-.078.733-.179 1.27-.482 2.463-1.278 3.572-2.126a59.907 59.907 0 0 0 1.62-1.297l.06-.05c.41-.338.81-.665 1.2-.971-.352.691-.915 1.622-1.41 2.44l-.13.216c-.316.523-.6.996-.727 1.263-.03.063-.068.149-.09.233-.007.03-.033.137-.005.264a.516.516 0 0 0 .504.405c.15 0 .26-.068.288-.084l.002-.001a.925.925 0 0 0 .116-.085 2.83 2.83 0 0 0 .21-.201 45.551 45.551 0 0 1 1.972-1.895l.17-.156a58.683 58.683 0 0 0 1.856-1.758c.842-.846 1.456-1.416 1.893-1.772l.096-.077c-.046.136-.102.288-.166.456-.081.213-.175.448-.273.693-.275.69-.585 1.471-.767 2.128-.12.44-.21.904-.155 1.29.03.2.103.425.277.604a.968.968 0 0 0 .662.286c.949.05 1.86-.346 2.704-.886.839-.537 1.677-1.26 2.486-1.96l.024-.02c.83-.718 1.633-1.409 2.432-1.923.038-.025.077-.05.116-.073-.431.382-.89.803-1.323 1.23-.403.396-.789.804-1.109 1.193-.315.383-.588.775-.743 1.14-.144.34-.252.83.071 1.229.296.364.807.454 1.323.448h.045l.043-.01c1.09-.209 1.969-.956 2.653-1.556.36-.316.65-.585.904-.834-.282.8-.272 1.498.058 2.069.42.724 1.25 1.05 2.076 1.177.845.13 1.814.072 2.694-.09.795-.148 1.56-.388 2.126-.684.122.016.238.021.328.025l.054.003c2.199.115 3.82-.676 5.494-1.924.606-.452 1.167-.94 1.707-1.435a54.157 54.157 0 0 1-1.706 2.267l-.006.008a.799.799 0 0 1-.022.023l-.072.074-.006.005c-.055.056-.129.13-.198.208-.07.08-.153.18-.218.293a.826.826 0 0 0-.12.5.518.518 0 0 0 .272.415.512.512 0 0 0 .6-.082.712.712 0 0 0 .107-.126 7.55 7.55 0 0 0 .113-.193l.026-.048.032-.054-.003.003c.292-.356.615-.695.95-1.044 1.298-1.355 2.636-2.7 4.079-3.855-.02.284-.047.565-.076.858-.027.276-.055.563-.078.869-.052.68-.072 1.398.045 2.08.069.4.257.75.619.936.336.173.713.145 1.034.064.64-.161 1.392-.623 2.079-1.119.703-.508 1.4-1.098 1.94-1.575.27-.24.503-.452.678-.612l.061-.056.002-.002a44.327 44.327 0 0 1 .223-.203l.022-.018.006-.006.002-.001a.5.5 0 1 0-.625-.78c-.055.043-.167.146-.302.27l-.064.058c-.174.16-.402.368-.666.601a25.12 25.12 0 0 1-1.862 1.514c-.681.49-1.3.849-1.74.96-.219.055-.31.027-.33.016-.007-.003-.017-.01-.032-.032a.51.51 0 0 1-.06-.183c-.095-.56-.083-1.179-.033-1.837.019-.254.045-.526.072-.802.039-.4.078-.808.098-1.177v-.009c.01-.2.02-.386.015-.526a1.065 1.065 0 0 0-.037-.255.602.602 0 0 0-.277-.36.593.593 0 0 0-.47-.046 1 1 0 0 0-.238.115c-.12.075-.267.191-.426.315-.39.305-.77.623-1.145.95l.09-.145c.054-.088.122-.191.195-.302l.045-.067c.082-.124.177-.27.236-.382.015-.03.033-.066.049-.105a.634.634 0 0 0 .044-.19.518.518 0 0 0-.275-.496c-.205-.107-.395-.038-.429-.025h-.002c-.106.039-.203.11-.263.155a5.124 5.124 0 0 0-.275.23c-.493.434-.97.886-1.44 1.33-.181.173-.362.345-.541.513-.65.609-1.298 1.192-2.002 1.716-1.245.928-2.377 1.53-3.723 1.693.838-.63 1.371-1.214 1.655-1.734.21-.384.308-.78.232-1.148a1.095 1.095 0 0 0-.678-.803c-.63-.255-1.452-.015-2.117.548-.69.584-1.288 1.564-1.541 2.982-.027.15-.033.311.002.467a7.853 7.853 0 0 1-1.416.393c-.806.15-1.657.194-2.36.086-.724-.111-1.173-.363-1.362-.69-.177-.305-.232-.864.302-1.865.459-.862.69-1.211.935-1.551l.152-.21c.221-.3.492-.669.926-1.346 1.582-1.82 4.037-5.746 5.047-7.894.063-.136.111-.244.14-.324a.822.822 0 0 0 .044-.163v-.002a.505.505 0 0 0-.826-.469v.001a.658.658 0 0 0-.068.064 1.23 1.23 0 0 0-.078.093 4.552 4.552 0 0 0-.147.209c-.104.155-.227.349-.331.514l-.05.078c-.084.133-.145.23-.17.266-.697 1.01-1.782 2.801-2.764 4.421a155.702 155.702 0 0 1-1.596 2.6c-.082.086-.318.314-.584.57l-.056.054-.002.002c-.254.245-.523.505-.604.594a103.7 103.7 0 0 0-.644.727c-.7.797-1.114 1.267-2.114 2.145-.696.61-1.37 1.155-2.138 1.318-.314 0-.438-.052-.477-.073 0-.03.01-.095.061-.215.098-.232.3-.535.594-.894.29-.352.65-.733 1.039-1.116.778-.767 1.654-1.524 2.286-2.064l.183-.156c.23-.196.42-.359.541-.467.039-.035.075-.068.105-.098h.001c.02-.02.07-.07.11-.13a.506.506 0 0 0-.331-.78.515.515 0 0 0-.255.02c-.942.023-1.841.428-2.676.965-.867.558-1.721 1.296-2.537 2l-.007.006c-.831.718-1.621 1.4-2.396 1.896-.775.496-1.47.762-2.107.73a.37.37 0 0 1-.007-.034c-.024-.166.013-.46.13-.881.165-.6.442-1.297.71-1.971.104-.259.206-.515.3-.76.16-.422.304-.834.36-1.152.026-.146.05-.353-.01-.545a.657.657 0 0 0-.231-.334.652.652 0 0 0-.402-.128c-.218.002-.425.102-.588.197-.18.105-.388.257-.626.45-.477.39-1.12.989-1.97 1.842a57.974 57.974 0 0 1-1.826 1.73l-.004.003c.399-.683.767-1.353.953-1.82.112-.284.195-.547.199-.764a.677.677 0 0 0-.151-.456.603.603 0 0 0-.512-.206.93.93 0 0 0-.318.09 2.131 2.131 0 0 0-.246.138c-.156.1-.328.229-.493.355-.486.373-.981.78-1.48 1.19l-.064.053c-.524.43-1.053.863-1.593 1.276-1.083.828-2.185 1.554-3.32 1.986-.213.08-.354.11-.44.115h-.009a.92.92 0 0 1 .005-.149c.023-.225.104-.518.212-.848l.11-.328c.073-.213.147-.43.196-.605.076-.268.27-.716.507-1.207.224-.466.472-.94.655-1.277.075-.1.144-.202.193-.298.045-.089.081-.163.101-.21a.614.614 0 0 0 .026-.076.5.5 0 0 0-.919-.385 8.26 8.26 0 0 0-.242.423c-.549.706-2.12 2.238-3.553 3.426-.662.548-1.263.997-1.7 1.253a5.53 5.53 0 0 1 .594-1.187c.364-.57.805-1.108 1.197-1.563 1.048-1.217 2.259-2.287 3.554-3.256.473-.354.817-.625 1.041-.818.11-.094.204-.18.27-.25a.929.929 0 0 0 .11-.139.577.577 0 0 0 .067-.153.513.513 0 0 0-.43-.646.564.564 0 0 0-.182.008.865.865 0 0 0-.168.054c-.086.037-.19.092-.302.156-.228.131-.546.332-.934.593-1.554 1.045-4.35 3.13-7.461 5.897-1.227 1.091-3.253 2.581-5.27 3.3-1.006.36-1.969.512-2.812.362-.822-.146-1.566-.585-2.157-1.49-1.42-2.176-1.485-5.246-.746-8.32C2.2 11.7 3.707 8.75 5.273 6.897 5.9 6.154 7.046 5.105 8.38 4.09c1.335-1.014 2.826-1.97 4.139-2.545.657-.288 1.246-.47 1.734-.526.493-.057.82.02 1.026.17.193.142.373.418.42.983.046.572-.052 1.387-.37 2.504-1.016 3.57-2.97 6.451-5.813 8.796a.5.5 0 0 0 .636.771zm37.654 8.075c.564-.357 1.009-.691 1.351-.995.437-.388.697-.717.838-.974.142-.261.142-.41.13-.465a.092.092 0 0 0-.02-.045.142.142 0 0 0-.055-.035c-.07-.029-.209-.048-.413.006-.199.053-.437.171-.68.378-.45.38-.911 1.057-1.151 2.13z"
                            fill="#000"
                          ></path>
                          <path
                            d="M86.246 3.07c-2.324-.334-4.835.557-7.173 2.081-2.348 1.53-4.582 3.738-6.374 6.148-1.792 2.408-3.165 5.05-3.762 7.46-.594 2.396-.446 4.685.996 6.231.461.494 1.1.76 1.772.892.675.132 1.425.14 2.164.086 1.477-.108 2.997-.476 3.93-.704a.5.5 0 0 0-.238-.971c-.939.23-2.383.576-3.765.678-.691.051-1.344.038-1.897-.07-.556-.11-.969-.308-1.234-.593-1.102-1.181-1.318-3.046-.758-5.308.557-2.247 1.857-4.768 3.594-7.104 1.736-2.334 3.887-4.452 6.118-5.907 2.24-1.46 4.502-2.214 6.484-1.93.563.081.909.261 1.121.472.21.207.334.489.373.864.08.783-.23 1.859-.78 3.047-1.086 2.348-2.941 4.798-3.492 5.503a.5.5 0 0 0 .788.616c.555-.71 2.473-3.239 3.612-5.699.562-1.215.976-2.501.867-3.569-.057-.55-.255-1.067-.664-1.472-.406-.403-.972-.65-1.682-.751z"
                            fill="#000"
                          ></path>
                          <path
                            fill-rule="evenodd"
                            clip-rule="evenodd"
                            d="M100.056 11.98a.854.854 0 0 1 .535.259c.482.482.607 1.167.558 1.855-.049.695-.279 1.478-.61 2.273-.632 1.517-1.678 3.173-2.772 4.512.136.304.352.487.614.592.3.12.68.141 1.082.066.4-.076.786-.243 1.081-.458.301-.22.461-.455.504-.65l.001-.003.002-.01.007-.037.004-.026.016-.084c.015-.084.036-.191.061-.293.021-.09.057-.222.112-.33l.001-.002a.598.598 0 0 1 .258-.265.525.525 0 0 1 .478.002c.846.23 1.688-.032 2.636-.487.239-.115.479-.24.725-.367l.058-.03.001-.001c.224-.117.454-.236.684-.35.498-.244 1.025-.471 1.569-.592.066-.015.159-.034.246-.034h.003a.55.55 0 0 1 .299.083.51.51 0 0 1 .196.633.584.584 0 0 1-.134.19h-.001a.94.94 0 0 1-.087.075 3.38 3.38 0 0 1-.179.122c-.079.052-.17.11-.272.173-.246.155-.553.348-.899.588a9.825 9.825 0 0 0-1.451 1.206c-.448.465-.789.957-.943 1.46-.113.366-.108.635-.051.778a.22.22 0 0 0 .093.117c.043.026.13.06.295.06.213 0 .495-.133.839-.458.332-.315.653-.743.939-1.177.204-.31.378-.603.527-.852l.17-.284c.077-.125.172-.278.261-.372a.661.661 0 0 1 .145-.115.525.525 0 0 1 .473-.025.53.53 0 0 1 .291.342c.02.074.023.141.023.179V22.4c0 .086.021.132.042.163.025.035.073.08.169.127.205.098.53.154.949.163.625.014 1.289-.073 1.792-.139.174-.022.328-.042.455-.055a.5.5 0 0 1 .099.995c-.086.008-.207.024-.352.043-.503.066-1.304.172-2.016.156-.461-.01-.96-.07-1.36-.262a1.411 1.411 0 0 1-.553-.452 1.263 1.263 0 0 1-.225-.74v-.562l-.055.083c-.301.457-.671.96-1.086 1.353-.403.381-.925.732-1.527.732-.302 0-.582-.063-.819-.208a1.22 1.22 0 0 1-.498-.599c-.181-.453-.117-.986.024-1.443.2-.65.599-1.23 1.053-1.725-.758.316-1.589.536-2.469.39l-.006.03-.011.062a5.009 5.009 0 0 1-.025.134c-.115.516-.476.938-.891 1.24-.422.309-.947.532-1.485.633-.535.101-1.118.088-1.638-.12a2.086 2.086 0 0 1-.935-.724c-.421.454-.843.855-1.249 1.173-.552.435-1.15.778-1.706.808a.779.779 0 0 1-.428-.098.79.79 0 0 1-.293-.294c-.118-.203-.15-.442-.16-.637-.018-.403.058-.91.14-1.358.017-.097.035-.19.053-.28l-.03.036a36.2 36.2 0 0 0-.42.526c-.234.296-.483.612-.724.892-.403.47-.86.936-1.364 1.227-.52.301-1.133.435-1.774.15a1.352 1.352 0 0 1-.715-.689c-.133-.3-.14-.626-.087-.93.08-.46.311-.955.612-1.433-.307.305-.615.622-.926.941l-.047.048-.227.234c-.747.766-1.511 1.532-2.27 2.105-.75.568-1.568 1.004-2.421 1.004-.47 0-.902-.136-1.169-.505-.25-.346-.265-.776-.211-1.152.108-.752.556-1.693 1.033-2.56.35-.637.742-1.28 1.078-1.828.129-.212.25-.409.356-.587.085-.141.159-.268.222-.38-1.175-.034-2.379.017-3.601.083l-.747.042c-1.196.068-2.407.137-3.595.137a.5.5 0 0 1 0-1c1.157 0 2.333-.067 3.528-.135h.002l.757-.042c1.449-.08 2.917-.139 4.354-.054a.55.55 0 0 1 .443.266.598.598 0 0 1 .078.364c-.013.142-.07.283-.116.384a9.17 9.17 0 0 1-.467.849 83.56 83.56 0 0 1-.374.615 45.29 45.29 0 0 0-1.042 1.767c-.48.874-.84 1.67-.92 2.222-.04.276.007.388.032.422.008.012.067.092.359.092.52 0 1.12-.274 1.818-.801.69-.522 1.405-1.235 2.157-2.006l.272-.28c.659-.678 1.342-1.38 2.03-1.98.78-.677 1.612-1.263 2.48-1.527.183-.056.476-.122.746-.181.29-.143.603-.255.899-.255.044 0 .114.001.182.014h.002c.019.004.14.026.247.12a.505.505 0 0 1 .058.705c-.072.087-.157.128-.175.137l-.002.001a.759.759 0 0 1-.082.035c-.043.015-.09.03-.134.041-.155.042-.402.096-.643.149l-.01.002c-.854.46-2.068 1.561-2.859 2.658-.406.564-.657 1.068-.722 1.44-.03.179-.012.29.017.355.024.055.073.12.206.18.266.118.536.09.868-.103.35-.203.717-.561 1.106-1.013.234-.273.45-.547.667-.823.151-.192.303-.384.462-.578.356-.434.752-.875 1.165-1.112a.579.579 0 0 1 .268-.077.535.535 0 0 1 .383.142.57.57 0 0 1 .153.24c.02.062.028.12.032.162.014.148-.01.332-.035.484-.029.18-.076.42-.126.668-.036.185-.074.375-.106.551-.083.451-.137.856-.124 1.133l.002.044c.232-.067.558-.242.968-.563.465-.366.978-.873 1.496-1.474-.015-.53.088-1.291.248-2.1.19-.955.473-2.046.798-3.047.323-.992.698-1.929 1.081-2.556.185-.302.41-.597.68-.764a.894.894 0 0 1 .543-.14zm-.44 4.002c-.422 1.013-1.052 2.11-1.759 3.12a26.488 26.488 0 0 1 .846-3.35c.316-.973.663-1.82.984-2.346.113-.186.207-.302.274-.37.143.201.224.516.19.988-.038.544-.225 1.215-.535 1.958z"
                            fill="#000"
                          ></path>
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section> */}

        {/* <section className="px-9 py-12">
          <div className="flex justify-between items-center">
            <div className="w-[44%]">
              <h2 className="text-3xl pb-10">
                Build with the top 7% of contractors in your area — local,
                vetted, licensed and insured
              </h2>
            </div>

            <button  onClick={openModal} className="bg-color4 rounded-lg text-white w-[350px] h-[50px]">
              Find A Contractor
            </button>
            <Modal isOpen={isModalOpen} closeModal={closeModal} />
          </div>
          <div className="flex gap-8">
            <Card
              backgroundImage={Constructor}
              circleImage={Woman}
              name="Dan"
              experience="7 years of experience"
            />

            <Card
              backgroundImage={Constructor}
              circleImage={Woman}
              name="Dan"
              experience="7 years of experience"
            />
            <Card
              backgroundImage={Constructor}
              circleImage={Woman}
              name="Dan"
              experience="7 years of experience"
            />
            <Card
              backgroundImage={Constructor}
              circleImage={Woman}
              name="Dan"
              experience="7 years of experience"
            />
          </div>
        </section> */}

        <section className="px-4 md:px-9 py-6 md:py-12">
          <div className="bg-milkgray w-full md:w-full h-auto md:h-[690px] rounded-2xl flex flex-col md:flex-row items-center justify-between p-4 md:p-0">
            <div className="flex flex-col gap-4 md:gap-7 md:pl-10">
              <div className="flex justify-center sm:flex">
                <p className="rounded p-1 text-color5 border inline-block">
                  Guarantee
                </p>
              </div>
              <p className="text-center text-2xl sm:text-4xl">
                2Go Project Protection
              </p>
              <p className="text-center sm:max-w-xs md:max-w-[580px] text-modaltext text-lg md:text-xl">
                Renovating is a risky business. 2Go makes your renovation more
                secure with guardrails to ensure your dream renovation is
                realized.
              </p>
            </div>

            <div className="flex flex-col gap-2.5 md:pr-10 w-full md:w-[600px]">
              {[
                "Professional Designers",
                "Great Communication",
                "Contractors Licensed & Insuranced",
                "Workmanship Warranty",
                "Pride In Our Work"
              ].map((item) => (
                <div className="border-b border-borderlight py-4 md:py-7 flex flex-row justify-between">
                  <p className="text-xl md:text-2xl">{item}</p>
                  <Image
                    className="w-7 md:w-9 h-7 md:h-9 mr-4 md:mr-6"
                    src={Done}
                    alt={""}
                  />
                </div>
              ))}
            </div>
          </div>
        </section>
      </Layout>
    </div>
  );
}
